name: e2e
# on:
#  pull_request:
#    branches:
#      - main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read-
jobs:
  e2e:
    name: e2e
    if: |
      startsWith(github.event.pull_request.title, 'fix:') ||
      startsWith(github.event.pull_request.title, 'feat:') ||
      startsWith(github.event.pull_request.title, 'feat(') ||
      startsWith(github.event.pull_request.title, 'feat!') ||
      startsWith(github.event.pull_request.title, 'refactor:')
    runs-on: ubuntu-latest
    env:
      VANUS_GATEWAY: 192.168.49.2:30001
      
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Environmental preparation
        run: |
          echo OK

